language: node_js
node_js:
- '8'
before_install:
- npm install
script:
- export BUILD_EXIT_VALUE="0"
- npm test || export BUILD_EXIT_VALUE="1"
before_deploy:
- echo "" > "${TRAVIS_BUILD_DIR}"/.gitignore
- npm run generate-test-report
deploy:
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: build/public
  on:
    branch: master
after_deploy:
- [[ $BUILD_EXIT_VALUE == "0" ]] && exit 0 || exit 1
env:
  global:
  - secure: XEWyha8eMdRAaLeL2fyAIRT6pDIScYUOIx7gt/DF10KbXuOhd8CCOP0qqF1OMH6OEYLAr6GD5kjP2IQkBb7v0dzc/umdZflmjZw0XanfAwoFRqLwm7rQQsiVSasTFj+q8Mmf05O4G0w3Hvr8RetO48IfKTiP/qgt+JYdxA0OV40M2eobY5/dSA+aaknrtnB1DOCS4o0PYWsMtDabXP4Cz5GPaYQ1yfImbPdf/UCufpLIDCpdJ714polhZv7DrbGqCtUNHdfQLW9j5p7ZhbkxXqPrtWVgWKa3QzJpxBOYvazHKgApCNlmGVmdHzP+wa5+ewkYt5zCDS6iiBX9mbn2mx3+mcPK6d4GrKi2pou7O9iA5VD4pGT6NVDsr2icW9W14celeuhVbbyBr/fYZIfz5iDbJdT+7yTn4WCP594HCWOwT4MsyS+CdsC0GPqpKmc4ooZWqyG+cpwbQvS1Tkal8Q6RUrRBlOPTcIOhfr9B6Z4mlLicmU1R1uqPfwCtsdO9fHJC8Y+d9h9hbzzOJplOTzRH/woHj3pPfeqFY1N5X7rUa0ih5We4XWYIdEvfKLkTrch5Wf+t6GY2zIiJXuR+IMmNmd8KZxmsezx26r48LB2ycdHxc2io43itiz3A7fRH4900qMjArIMAmQ1z7makOXSveq9mS7rg1AFFntU0250=
  - secure: TlekYJFVgnkcvHXZ2Tf/GXMJhOITSbTMDRpPIFeW72l+7BHd1Ljgd+3O6T8NefeDlsdGpeVjTARP6M32xdm+T1Y4pvn503L2XY27pQJL57R14nmyqqqkR0xlbL/aSreg1X2BDL8XD6CPRSKSciblI+eTxgk/vGk5jK1qSwbxPAwuZJ7rOMGYU+SxNftdsfuk28shq1wPYRg4uUJMhJ39eBNvaj32PnEpAzkX+sTf+pglNC0k6R1PcfwMiOpEurEnnwfpSFzRs5MOv7kbJLtOPxJLdu1laTsnMXHTKMPtgbBq02loq9QZgYxbbC4/B08i1mKaOtePGxHJQr+lq4KxWQyzJFTnbwVEhp09WhIXgqBXSTGxXrbgxiwWNesg3URdkfh8Hzf8ZOZz1xakc19xEgUvByC4ZqCNjdjvewzEwdnw/dlv5aNHsMUUQ69OY+1e4OrXpSoedtWlMN+Qnnd6IJQMYmDm68kqXpJYK4thhI0QBST81rlwHTe2jq9WzpSwYaU6H2ewvlIkidHE69JUWIhs5Mij27YTyxtf6whokby+D49/mj3dQ8s8CVVWWyqez3efPNJ1DZ2V+j+J9D83X/jmVqPIxXnzumMe50UCqtU1Rp6l6tCcwGm54Ny6uWwRl87tdH4zxM75qX1FtWJA55mGP8fOMWqbgTKiztF8X6o=
  - secure: bdasalb98pv/I8llxvQslequ50iWX9hdpv2kJsypcm293iw2KfJxJXEeiTKt6d5fs2ZFDy4GKsyBgPyzR1w8EoxeH+Q+z+3Vdg+UxvnnpprXz7HEc9jVyhTXEBMt7A9XAtABSbgcrtzTLqjYtbVXCO0uk4NAIFszwiuElUBEoqLA1d1slj6gETtF7H1IVnkaAp6MYoASlKyyH23KjPcmt7PU78g5QwlZcEtcqHBG72i/DMTEt1f+NXpyI0qgwmssubL6Pv7GdN0vZ236fdjtw7XjTp1lU4Slh259whNQB9u8bB4+UUhHwHhPnEjRBCxutH4c0rfH4UQuWGnd1ntDVkObJPqhoF5iUsfikMDMhbZjIvQiWBurr35Xz7wJ1Cq9G1NoLHxFyJ45hmeNtZ5H1vj8ubUiVagK0YVYD9v7dciPO98XbrKLAykuyuUGSqy0rzxHLNd4JoFlIRRg2ZI2GNfqagY28Pnt1gMuGowiAouc0RF1YNGsMFBTrBCW32e1AP1Vbv5mdAwKTJS64MskCII9vnuiTW+nB5Oo4MSZsA297a04oEVP5HJqVm5KWHNvAnbMG2D3nA2M3nlM3mMnjq9Ed3k1/rGQOsyzA/T/1OKEkLmIuv5wlJ0rH2lZq+96jGa4mJapwiY2UhVoQ6kTjuMVhbB9Vn4ePDNpwp80wA0=
